### ISSUE TITLE
Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by zymergen-mbarton** [rabix/composer#428]
When trying to join an expression tool node in my workflow to another node I
get an unclosable window with the following error message. I have to force quit
rabix to get around this.

```
An error has occured

Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.
    at Function.t.Edge.e.spawn (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:704152)
    at Function.t.Edge.e.spawnBetweenConnectionIDs (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:705318)
    at e.t.Workflow.e.onConnectionCreate (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2760737)
    at e.D3uq.t.EventHub.e.emit (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:882809)
    at t.SXoy.t.WorkflowModel.t.connect (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1649751)
    at t.KYU0.t.SVGPortDragPlugin.t.createEdgeBetweenPorts (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1184566)
    at t.KYU0.t.SVGPortDragPlugin.t.onMoveEnd (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1180757)
    at HTMLDocument.h (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2808535)
    at t.ZSR1.t.invokeTask (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/polyfills.3f6e125d1164e75ce6cd.bundle.js:1:22059)
    at Object.onInvokeTask (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1758401)
 Report
Close
An error has occured

Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.
    at Function.t.Edge.e.spawn (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:704152)
    at Function.t.Edge.e.spawnBetweenConnectionIDs (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:705318)
    at e.t.Workflow.e.onConnectionCreate (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2760737)
    at e.D3uq.t.EventHub.e.emit (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:882809)
    at t.SXoy.t.WorkflowModel.t.connect (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1649751)
    at t.SXoy.t.WorkflowModel.t._createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1653895)
    at t.V1WorkflowModel.t.createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:4619870)
    at t.KYU0.t.SVGPortDragPlugin.t.onMoveEnd (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1181002)
    at HTMLDocument.h (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2808535)
    at t.ZSR1.t.invokeTask (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/polyfills.3f6e125d1164e75ce6cd.bundle.js:1:22059)
 Report
Close
An error has occured

Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.
    at Function.t.Edge.e.spawn (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:704152)
    at Function.t.Edge.e.spawnBetweenConnectionIDs (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:705318)
    at e.t.Workflow.e.onConnectionCreate (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2760737)
    at e.D3uq.t.EventHub.e.emit (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:882809)
    at t.SXoy.t.WorkflowModel.t.connect (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1649751)
    at t.SXoy.t.WorkflowModel.t._createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1653895)
    at t.V1WorkflowModel.t.createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:4619870)
    at t.KYU0.t.SVGPortDragPlugin.t.onMoveEnd (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1181002)
    at HTMLDocument.h (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2808535)
    at t.ZSR1.t.invokeTask (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/polyfills.3f6e125d1164e75ce6cd.bundle.js:1:22059)
 Report
Close
An error has occured

Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Filter empty FASTQ files') contains HTML space characters, which are not valid in tokens.
    at Function.t.Edge.e.spawn (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:704152)
    at Function.t.Edge.e.spawnBetweenConnectionIDs (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:705318)
    at e.t.Workflow.e.onConnectionCreate (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2760737)
    at e.D3uq.t.EventHub.e.emit (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:882809)
    at t.SXoy.t.WorkflowModel.t.connect (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1649751)
    at t.SXoy.t.WorkflowModel.t._createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1653895)
    at t.V1WorkflowModel.t.createOutputFromPort (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:4619870)
    at t.KYU0.t.SVGPortDragPlugin.t.onMoveEnd (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:1181002)
    at HTMLDocument.h (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/main.42b289bf4279e2838d08.bundle.js:1:2808535)
    at t.ZSR1.t.invokeTask (file:///Applications/rabix-composer.app/Contents/Resources/app.asar/polyfills.3f6e125d1164e75ce6cd.bundle.js:1:22059)
```

**Comment by zymergen-mbarton** [comment]
The source of this looks to be `id:` fields with spaces in. I had incorrectly entered spaces in the id field when I was manually editting the CWL to add an expression tool to my workflow. Possibly related to #407.

**Comment by kaushik-work** [comment]
@zymergen-mbarton Thanks for reporting this. We are working on improving sanitizing the id field (as discussed in #417 ) and we should also be trapping this error and not giving you an un-closable modal error box. I've run into this a few times and it is indeed very annoying. Sorry.
