### ISSUE TITLE
"Cannot find module 'node-sass'" and 'Invalid CSS after "&:not(...' during `yarn run serve` on MacOS

### ISSUE THREAD

**Issue by chrisbarber** [rabix/composer#433]
MacOS 10.13.6 (17G2208)
yarn 1.13.0
node v11.10.1
npm 6.7.0
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

Steps:
```bash
brew install yarn
brew install homebrew/cask/java
git clone https://github.com/rabix/composer
cd composer
git checkout release/v1.0.1
yarn install
yarn run serve &
```
First error:
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/assets/sass/main.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/barberc/repos/composer/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (/Users/barberc/repos/composer/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:173:18
ERROR in webpack-internal:///./src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:1
throw new Error("Module build failed: Error: Cannot find module 'node-sass'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:539:25)\n    at Module.require (internal/modules/cjs/loader.js:667:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/barberc/repos/composer/node_modules/sass-loader/lib/loader.js:3:14)\n    at Module._compile (internal/modules/cjs/loader.js:738:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)\n    at Module.load (internal/modules/cjs/loader.js:630:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:3)\n    at Module.require (internal/modules/cjs/loader.js:667:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at loadLoader (/Use

Error: Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/barberc/repos/composer/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (/Users/barberc/repos/composer/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/barberc/repos/composer/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at eval (webpack-internal:///./src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:1:7)
    at Object../src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss (/Users/barberc/repos/composer/src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:71:1)
    at __webpack_require__ (/Users/barberc/repos/composer/src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:20:30)
    at /Users/barberc/repos/composer/src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:63:18
    at /Users/barberc/repos/composer/src/app/tool-editor/tool-visual-editor/tool-visual-editor.component.scss:66:10
    at Script.runInContext (vm.js:135:20)
    at Script.runInNewContext (vm.js:141:17)
    at Object.runInNewContext (vm.js:307:38)
    at WebpackResourceLoader._evaluate (/Users/barberc/repos/composer/node_modules/@ngtools/webpack/src/resource_loader.js:110:40)
    at Compilation.compilation.plugin (/Users/barberc/repos/composer/node_modules/@ngtools/webpack/src/resource_loader.js:58:26)
```
Workaround:
```
mv package-lock.json package-lock.json.bak && npm i
```
(based on https://github.com/npm/registry-issue-archive/issues/347#issuecomment-397061950)

Again:
```bash
yarn run serve &
```
Second error:
```
ERROR in webpack-internal:///./src/app/layout/action-bar/action-bar.component.scss:1
throw new Error("Module build failed: \n        &:not(\".text-inherit\") {\n             ^\n      Invalid CSS after \"        &:not(\": expected selector, was '\".text-inherit\") {'\n      in /Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)");//# sourceURL=[module]
^

Error: Module build failed: 
        &:not(".text-inherit") {
             ^
      Invalid CSS after "        &:not(": expected selector, was '".text-inherit") {'
      in /Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)
    at eval (webpack-internal:///./src/app/layout/action-bar/action-bar.component.scss:1:7)
    at Object../src/app/layout/action-bar/action-bar.component.scss (/Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss:71:1)
    at __webpack_require__ (/Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss:20:30)
    at /Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss:63:18
    at /Users/barberc/repos/composer/src/app/layout/action-bar/action-bar.component.scss:66:10
    at Script.runInContext (vm.js:135:20)
    at Script.runInNewContext (vm.js:141:17)
    at Object.runInNewContext (vm.js:307:38)
    at WebpackResourceLoader._evaluate (/Users/barberc/repos/composer/node_modules/@ngtools/webpack/src/resource_loader.js:110:40)
    at Compilation.compilation.plugin (/Users/barberc/repos/composer/node_modules/@ngtools/webpack/src/resource_loader.js:58:26)
```
Workaround: delete/comment lines 17-19 in `src/app/layout/action-bar/action-bar.component.scss`.

Finally:
```bash
yarn run serve &
yarn run compile:electron
yarn run start:electron
```
(no more issues)

**Comment by kaushik-work** [comment]
Thanks @chrisbarber for this detailed report and even implementing a fix!

**Comment by kaushik-work** [comment]
@chrisbarber 

I have the following setup

MacOS 10.13.6
yarn 1.13.0
node v11.11.0 (worked with a much earlier version too)
npm 6.7.0

In a fresh directory
```
yarn install

yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...

....
```

There are some errors, but it does finish

```
yarn run serve &
...

WARNING in Circular dependency detected:
src/app/core/modals/add-source-modal/add-source-modal.component.ts -> src/app/core/modals/platform-credentials-modal/platform-credentials-modal.component.ts -> src/app/layout/notification-bar/dynamic-notifications/get-started-notification/get-started-notification.component.ts -> src/app/core/modals/add-source-modal/add-source-modal.component.ts

...
(similar warnings which I've seen before)
...
webpack: Compiled with warnings.

yarn run compile:electron
yarn run start:electron
```
Seems to work fine.

I wonder what else is different between our setups.

**Comment by SooLee** [comment]
I have exactly the same error.
OS : Mac 10.13.6
yarn 1.15.2
node 11.14.0
npm 6.9.0

**Comment by gungorbudak** [comment]
I think this is related to the `node` version during `package-lock.json` or `yarn.lock` is created and the package versions used back then. I had the same issue with `node v12.10.0` and had to delete lock files as @chrisbarber did to solve it. Because the `node-sass` version in lock file seems to be [supported](https://github.com/sass/node-sass/releases/tag/v4.7.2) by `node` upto `9`, I also tried downgrading `node` to a lower version which is `v8.16.2` from `brew` and it worked keeping available lock files in the repository.

My setup:
macOS 10.15
node 8.16.2
npm 6.4.1
yarn 1.17.3

Commands to downgrade `node` with `brew`:
```
brew unlink node
brew install node@8
brew link --overwrite node@8
```

Then these commands to serve:
```
git clone https://github.com/rabix/composer
cd composer
git checkout release/v1.0.1
yarn install
yarn run serve &
yarn run compile:electron
yarn run start:electron
```

**Comment by wcc526** [comment]
I have the same error

**Comment by kaushik-work** [comment]
Thanks so much @gungorbudak . 

I've updated the build instructions on the Readme with this node (17c4620). It will be merged with master soon. In an upcoming release we aim to pay down a bunch of technical debt and update dependencies and frameworks as needed. 

Thanks!
