### ISSUE TITLE
Illegal character when testing workflows and tools in Rabix Composer

### ISSUE THREAD

**Issue by Silberbear** [rabix/composer#437]
I am new to Rabix and CWL in general. I am just trying to understand how to run my tools from the Rabix Composer on Windows 10. However, everytime I go to test a tool or workflow it gives me the following error

`Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\pkara\RabixComposer\Executions\local\hello_world\2019-08-19-13-30-30\app.cwl
`

This is the tools I am trying to run

```
class: CommandLineTool
cwlVersion: v1.0
$namespaces:
  sbg: 'https://www.sevenbridges.com/'
id: hello_world
baseCommand:
  - echo
inputs:
  - id: input
    type: string
    inputBinding:
      position: 0
outputs: []
label: hello_world
```

And this is the full Error Log Output

```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\pkara\RabixComposer\Executions\local\hello_world\2019-08-19-13-30-30\app.cwl
	at java.net.URI.create(Unknown Source)
	at org.rabix.cli.BackendCommandLine.main(BackendCommandLine.java:122)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\pkara\RabixComposer\Executions\local\hello_world\2019-08-19-13-30-30\app.cwl
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	... 2 more
```

It seems to me, that the path, that is generated is not being read correctly by Rabix

For reference I am running Rabix Composer 1.0.1 on Windows 10

**Comment by kaushik-work** [comment]
Hi @Silberbear thanks for reporting this issue. Unfortunately, this is a problem with Rabix Executor on Windows. We've investigated this issue previously and verified that Composer is passing the command line correctly to the executor. (If you discover otherwise, please comment).

**Comment by Silberbear** [comment]
Did anyone find a way to fix this issue? Or does it just not work for now? Thank you for the reply.

**Comment by mmm2006** [comment]
It happen in my side too. I don't know how to do it. Any one can help me? Thanks.

**Comment by mmm2006** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\ThinkPad\RabixComposer\Executions\local\two_samples_ttest\2021-03-12-18-49-18\app.cwl
	at java.net.URI.create(URI.java:852)
	at org.rabix.cli.BackendCommandLine.main(BackendCommandLine.java:122)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\ThinkPad\RabixComposer\Executions\local\two_samples_ttest\2021-03-12-18-49-18\app.cwl
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 1 more
