### ISSUE TITLE
1.0.1 "yarn run build" failing 

### ISSUE THREAD

**Issue by truatpasteurdotfr** [rabix/composer#438]
Hi

I am trying to build the following procedre fails with:
```
root@8befb79dcbb8:/composer# yarn run build
yarn run v1.19.1
$ ./node_modules/.bin/rimraf dist ng-dist && yarn run compile:electron && yarn run compile:angular && yarn run package
$ ./node_modules/.bin/rimraf electron/dist electron/ng-dist && ./node_modules/.bin/tsc -p electron && node build-scripts/splash-copy.js
$ node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build -prod -aot
 10% Date: 2019-11-14T09:01:09.956Z                                                     
Hash: 0b0a7fd7ce3fa61725df
Time: 8303ms
chunk {0} styles.8f1522e20d8d802baa2c.bundle.css (styles) 151 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in /composer/src/app/layout/action-bar/action-bar.component.scss:71
throw new Error("Module build failed: \n        &:not(\".text-inherit\") {\n             ^\n      Invalid CSS after \"        &:not(\": expected selector, was '\".text-inherit\") {'\n      in /composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)");
^

Error: Module build failed: 
        &:not(".text-inherit") {
             ^
      Invalid CSS after "        &:not(": expected selector, was '".text-inherit") {'
      in /composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)
    at Object.rZm9 (/composer/src/app/layout/action-bar/action-bar.component.scss:71:7)
    at __webpack_require__ (/composer/src/app/layout/action-bar/action-bar.component.scss:20:30)
    at /composer/src/app/layout/action-bar/action-bar.component.scss:63:18
    at /composer/src/app/layout/action-bar/action-bar.component.scss:66:10
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at Object.runInNewContext (vm.js:299:38)
    at WebpackResourceLoader._evaluate (/composer/node_modules/@ngtools/webpack/src/resource_loader.js:110:40)
    at Compilation.<anonymous> (/composer/node_modules/@ngtools/webpack/src/resource_loader.js:58:26)
    at Compilation.applyPluginsAsyncSeries (/composer/node_modules/tapable/lib/Tapable.js:206:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

```
$ sudo docker pull node
$ sudo docker images node
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/node      latest              1a77bcb355eb        6 days ago          933 MB

$ sudo docker run -ti node bash
apt-get update && apt-get -y upgrade
apt-get -y install git default-jdk
git clone https://github.com/rabix/composer
cd composer
git checkout release/v1.0.1
yarn install
yarn run build
# error missing node-sass
yarn add node-sass
# error this bug entry
```

**Comment by gungorbudak** [comment]
Hi @truatpasteurdotfr,

Thanks for reporting this! Please also see #433.

The `node-sass` version required by Composer does not play well with latest `node`so you should consider using the matching node version which is `8`.  See [the version table here](https://github.com/sass/node-sass#node-sass).

So you will succeed with (slightly modified your commands):

```
$ docker pull node:8-jessie
$ docker run -ti node:8-jessie bash
apt-get update && apt-get -y upgrade
apt-get -y install git default-jdk
git clone https://github.com/rabix/composer
cd composer
git checkout release/v1.0.1
yarn install
yarn run build
```

@kaushik-work Node 8 will reach to EOL this year we might plan to work with dependencies so they are compatible with Node 12.

**Comment by kaushik-work** [comment]
Thanks for replying @gungorbudak ! OK, let us plan to do that. This will be a conversation with @marijanlekic and other members of the team probably.

**Comment by truatpasteurdotfr** [comment]
thx, I was not aware of node-sass <-> node dependancy. I have successfully run the build recipe against node:8-buster (instead of node:8-jessie as jessie LTS will also EOL in june 2020) and node:8-alpine (3.9 with openjdk-8).
