### ISSUE TITLE
which node version requriments?

### ISSUE THREAD

**Issue by wcc526** [rabix/composer#448]
which node version requriments?

the compose could not yarn run on MacOS

Please help.

Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by marijanlekic** [comment]
Which node version are you using?

**Comment by wcc526** [comment]
node --version                                                                                                                                                                                                                                                      
v10.19.0

ERROR in webpack-internal:///./src/app/layout/action-bar/action-bar.component.scss:1
throw new Error("Module build failed: \n        &:not(\".text-inherit\") {\n             ^\n      Invalid CSS after \"        &:not(\": expected selector, was '\".text-inherit\") {'\n      in /Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)");//# sourceURL=[module]
^

Error: Module build failed:
        &:not(".text-inherit") {
             ^
      Invalid CSS after "        &:not(": expected selector, was '".text-inherit") {'
      in /Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss (line 17, column 15)
    at eval (webpack-internal:///./src/app/layout/action-bar/action-bar.component.scss:1:7)
    at Object../src/app/layout/action-bar/action-bar.component.scss (/Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss:71:1)
    at __webpack_require__ (/Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss:20:30)
    at /Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss:63:18
    at /Users/wcc526/Projects/composer/src/app/layout/action-bar/action-bar.component.scss:66:10
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17)
    at Object.runInNewContext (vm.js:322:38)
    at WebpackResourceLoader._evaluate (/Users/wcc526/Projects/composer/node_modules/@ngtools/webpack/src/resource_loader.js:110:40)

**Comment by marijanlekic** [comment]
The easiest/fastest way is to remove this part of a code:

    /deep/ .btn:not(".text-inherit") {
        font-size: $font-size-base;
    }

from action-bar.component.scss file and it should work...

**Comment by wcc526** [comment]
but what the recommend node version? node 8 or node 12?

**Comment by marijanlekic** [comment]
Initially, it was made with node 8 and angular 5 and dependencies were not updated. It should work with the newer version of Node as well (not quite sure about the build process). Basically, when starting with "serve" command it should work well (except this node-sass issue).

**Comment by wcc526** [comment]
$ docker pull node:8-jessie
$ docker run -ti node:8-jessie bash
apt-get update && apt-get -y upgrade
apt-get -y install git default-jdk
git clone https://github.com/rabix/composer
cd composer
yarn install
yarn run build

**Comment by marijanlekic** [comment]
is it working?

**Comment by kaushik-work** [comment]
@wcc526 this should now compile on more recent node versions, certainly 14.x

Closed by 2ed476828727830ec669404d36d0c9adaf2f0ad0
